site_name: EKG
docs_dir: source
site_dir: docs

theme:
    name: readthedocs

nav:
    - 'Getting Started':
        - Installation: installation.md
        - Creating a GUI: creating-a-gui.md

    - 'UI':
        - Abstract: abstract.md
        - Button: button.md
        - Checkbox: checkbox.md
        - Listbox: listbox.md
        - Textbox: textbox.md

    - 'Service':
        - Input: input.md
        - Handler: handler.md
        - Allocator: allocator.md

    - 'GPU':
        - OpenGL API: opengl-api.md
        - Vulkan API: vulkan-api.md

    - 'Utility':
        - item.md

    - 'FAQ':
        - Motivation: faq-motivation.md
        - Contributing: faq-contributing.md